print("Olá mundo")
print("Francisco", "Lucas", "Janesch", "Lange", "Sens")
print("Soma: ", 2 + 2)
print("Subtrair: ", 2 - 2)
print("Mulitiplicar: ", 2 * 2)
print("Dividir: ", 5 / 2)
print()
print("     *")
print("    ***")
print("   *****")
print("  *******")
print(" *********")
print("    ***")
print("    ***")
# https://dontpad.com/franciscosensaulas/python